Use generic run all function for running the tests
sclorg/s2i-nodejs-container pull request #356
Opened 2022-09-21 07:11 UTC by zmiklank

2022-09-21 07:13 UTC, zmiklank commented
[test-all]

2022-09-27 13:49 UTC, zmiklank commented
[test-all]

2022-09-27 13:51 UTC, zmiklank commented
[test-all]

2022-10-06 06:46 UTC, zmiklank commented
[test-all]

2022-10-20 06:20 UTC, zmiklank commented
[test-all][ENV:DEBUG=1]

2022-10-20 10:27 UTC, zmiklank commented
same problem as in https://github.com/sclorg/s2i-nodejs-container/issues/365

2022-10-21 11:06 UTC, zmiklank commented
[test-all]

2022-10-25 11:47 UTC, phracek requested changes
Just one. And when this is solved, we can merge it.

2022-10-25 13:19 UTC, zmiklank commented on 14-minimal/root/opt/app-root/etc/generate_container_user
> -    export LD_PRELOAD=libnss_wrapper.so
Because nss_wrapper is not used in minimal images.
But thank you for pointing it out, this should be done differently. I will rework it.

2022-11-07 11:41 UTC, zmiklank commented
@pkubatrh Could you please review if the way of removing `nss_wrapper` from minimal images is correct?

2022-11-14 07:56 UTC, zmiklank commented
[test-all]

2022-11-22 09:46 UTC, phracek commented
[test-all]

2022-11-24 13:02 UTC, phracek approved these changes
LGTM. Let's get merge it.

2022-11-24 13:02 UTC, phracek commented
[test-all]

2022-11-24 14:40 UTC, merged